#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage: bash scripts/submit_train.sh configs/cross_location_resnet18.yaml"
  exit 1
fi

if [[ -z "${ACCOUNT:-}" || -z "${PROJECT_ROOT:-}" || -z "${ENV_PREFIX:-}" || -z "${DATA_ROOT:-}" || -z "${OUTPUT_ROOT:-}" ]]; then
  echo "Set ACCOUNT, PROJECT_ROOT, ENV_PREFIX, DATA_ROOT, and OUTPUT_ROOT before running."
  exit 1
fi

CONFIG_PATH="$1"
TRAIN_INTERVENTION="${TRAIN_INTERVENTION:-${2:-}}"
VISIBILITY_MODE="${VISIBILITY_MODE:-}"
VISIBILITY_SCOPE="${VISIBILITY_SCOPE:-}"
NIGHT_ONLY_FLAG_SOURCE="${NIGHT_ONLY_FLAG_SOURCE:-}"
VISIBILITY_GAMMA="${VISIBILITY_GAMMA:-}"
VISIBILITY_CLAHE_CLIP_LIMIT="${VISIBILITY_CLAHE_CLIP_LIMIT:-}"
VISIBILITY_CLAHE_TILE_GRID_SIZE="${VISIBILITY_CLAHE_TILE_GRID_SIZE:-}"
EVAL_ONLY_CHECKPOINT="${EVAL_ONLY_CHECKPOINT:-}"
CHECKPOINT_RESULTS_ROOT="${CHECKPOINT_RESULTS_ROOT:-}"
SEED="${SEED:-}"
LOSS="${LOSS:-}"
CLASS_WEIGHT_MODE="${CLASS_WEIGHT_MODE:-}"
TRAIN_SAMPLER="${TRAIN_SAMPLER:-}"
FOCAL_GAMMA="${FOCAL_GAMMA:-}"
IMAGE_ABLATION="${IMAGE_ABLATION:-}"
IMAGE_ABLATION_BBOX_PADDING_FRACTION="${IMAGE_ABLATION_BBOX_PADDING_FRACTION:-}"
IMAGE_ABLATION_MASK_FEATHER="${IMAGE_ABLATION_MASK_FEATHER:-}"
IMAGE_ABLATION_FILL_COLOR="${IMAGE_ABLATION_FILL_COLOR:-}"

sbatch \
  --account="$ACCOUNT" \
  --partition="${PARTITION:-gpu}" \
  --job-name="${JOB_NAME:-cct20_train}" \
  --gres="gpu:${GPUS:-1}" \
  --cpus-per-task="${CPUS_PER_TASK:-8}" \
  --mem="${MEMORY:-48G}" \
  --time="${TIME_LIMIT:-08:00:00}" \
  --export=ALL,PROJECT_ROOT="$PROJECT_ROOT",ENV_PREFIX="$ENV_PREFIX",DATA_ROOT="$DATA_ROOT",OUTPUT_ROOT="$OUTPUT_ROOT",CONFIG_PATH="$CONFIG_PATH",TRAIN_INTERVENTION="$TRAIN_INTERVENTION",VISIBILITY_MODE="$VISIBILITY_MODE",VISIBILITY_SCOPE="$VISIBILITY_SCOPE",NIGHT_ONLY_FLAG_SOURCE="$NIGHT_ONLY_FLAG_SOURCE",VISIBILITY_GAMMA="$VISIBILITY_GAMMA",VISIBILITY_CLAHE_CLIP_LIMIT="$VISIBILITY_CLAHE_CLIP_LIMIT",VISIBILITY_CLAHE_TILE_GRID_SIZE="$VISIBILITY_CLAHE_TILE_GRID_SIZE",EVAL_ONLY_CHECKPOINT="$EVAL_ONLY_CHECKPOINT",CHECKPOINT_RESULTS_ROOT="$CHECKPOINT_RESULTS_ROOT",SEED="$SEED",LOSS="$LOSS",CLASS_WEIGHT_MODE="$CLASS_WEIGHT_MODE",TRAIN_SAMPLER="$TRAIN_SAMPLER",FOCAL_GAMMA="$FOCAL_GAMMA",IMAGE_ABLATION="$IMAGE_ABLATION",IMAGE_ABLATION_BBOX_PADDING_FRACTION="$IMAGE_ABLATION_BBOX_PADDING_FRACTION",IMAGE_ABLATION_MASK_FEATHER="$IMAGE_ABLATION_MASK_FEATHER",IMAGE_ABLATION_FILL_COLOR="$IMAGE_ABLATION_FILL_COLOR",SMOKE=0 \
  "$PROJECT_ROOT/slurm/train_job.sh"
